[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
    "python3.11 -m ensurepip --upgrade",
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install -r requirements.txt",
    "python3.11 train_model.py"
]

[start]
cmd = "python3.11 -m gunicorn app:app"